# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=7046
@host={{hostname}}:{{port}}

### Upload a file named PARRA.jpg
POST http://{{host}}/api/upload/PARRA.jpg
Content-Type: application/octet-stream

< ./assets/PARRA.jpg
###

### Upload a file named PARRA.jpg
GET http://{{host}}/api/external
###